### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by jinzhongjia** [rafaelbreno/zig-os#2]
Hey, I recently learn zig and about os build, and I learn many from your code and osdev

Now, I have two questions, one is how to make `\n` taking effect ?  Now, I will just show character `\n`
Do we need to filter characters in the code?

 Another one is that I found some dsplay error when I try to change the VGA_WIDTH and VGA_HEIGHT to like number `20` `5`,  I expected it to just reduce the number of rows displayed

![图片](https://user-images.githubusercontent.com/41784264/224005685-c3092e90-c2bc-4132-b820-d45b6aa7f271.png)

**Comment by jinzhongjia** [comment]
OK, I have found it
![图片](https://user-images.githubusercontent.com/41784264/224029938-0d59043d-4d2e-40b8-be25-a9280b66eda4.png)

**Comment by jinzhongjia** [comment]
I have found one, according to osdev wiki
 
**Adding Support for Newlines to Terminal Driver**

> The current terminal driver does not handle newlines. The VGA text mode font stores another character at the location, since newlines are never meant to be actually rendered: they are logical entities. Rather, in terminal_putchar check if c == '\n' and increment terminal_row and reset terminal_column.

**Comment by rafaelbreno** [comment]
Hi @jinzhongjia thanks for the issue, so, answering your questions:

> Now, I have two questions, one is how to make \n taking effect ? Now, I will just show character \n
Do we need to filter characters in the code?

Basically what we're doing in this kernel is, we're literally handling each byte(`u8`) from our buffer that is shown on our terminal, meaning: if we want to add a `\n` we would need to skip the current row, and just to the next one before adding the next character. 
That is something that I'll be doing in the next "chapter": a `fmt` package and keyboard handling.

> Another one is that I found some dsplay error when I try to change the VGA_WIDTH and VGA_HEIGHT to like number 20 5, I expected it to just reduce the number of rows displayed

Well, I search a little about it, and did some tests, basically that message is shown because we didn't cleaned the buffer, that's the old message, if you change your `_start()`:
```zig
// from:
export fn _start() callconv(.Naked) noreturn {
    term.initialize();
    term.write("Hello, World!");
    while (true) {}
}

// to:
export fn _start() callconv(.Naked) noreturn {
    while (true) {}
}
```

You will see the old message in the buffer.

And thanks for the interest in the project, in the future I'm thinking about makings this project flexible to work on another architectures like `RISC-V` :D
